databases:
  - name: InfoHud_DB
    databaseName: infohud_db_973k
    user: admin

services:
  - type: web
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn projeto.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: projeto
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4