# Generated by Django 4.2.7 on 2023-12-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=40)),
                ('miniurl', models.CharField(blank=True, max_length=150, null=True)),
                ('conteudo', models.CharField(max_length=500, null=True)),
                ('user_nickname', models.CharField(editable=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='oi',
        ),
    ]
