# Generated by Django 4.2.7 on 2023-12-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_postagens_usuarios_delete_oi'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagens',
            name='categoria',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
