# Generated by Django 4.2.7 on 2023-12-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_postagens_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagens',
            name='user_nickname',
            field=models.CharField(max_length=50),
        ),
    ]
