# Generated by Django 4.2.7 on 2023-12-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usuarios_bibliografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='bibliografia',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
