# Generated by Django 4.2.7 on 2024-01-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_usuarios_bibliografia_usuarios_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagens',
            name='conteudo',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='postagens',
            name='miniurl',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='postagens',
            name='subtitulo',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='postagens',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
